### ISSUE TITLE
Multiprocessing?

### ISSUE THREAD

**Issue by yohanboniface** [addok/addok-sqlite-store#2]
We crashed the DB when importing with 24 cores.

sqlite was complaining about db being corrupted:

> Database disk image is malformed.

Sqlite3 documentation says:

> When a database is accessed by multiple connections, and one of the processes modifies the database, the SQLite database is locked until that transaction is committed.

Needs investigation.

**Comment by cquest** [comment]
En limitant à 8 process sur ma workstation ça passe, avec 24 ça plante...

**Comment by yohanboniface** [comment]
cf https://github.com/addok/addok/issues/237
